import type { AppProps } from 'next/app'
import Head from 'next/head'

import 'aether-css-framework/dist/aether.min.css'
import '@/styles/globals.css'
import packageJson from '../package.json'

const App: React.FC<AppProps> = ({ Component, pageProps }) => (
  <>
    <Head>
      <title>{packageJson.description}</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <Component {...pageProps} />
  </>
)
export default App
